repos:
- repo: local
  hooks:
  - id: mypy
    name: mypy
    always_run: true
    require_serial: true
    pass_filenames: false

    language: python
    entry: bash -c ". ${PRE_COMMIT_MYPY_VENV:-/dev/null}/bin/activate 2>/dev/null; mypy $0 $@"
    additional_dependencies:
    - mypy >= 1.8.0
    - genno
    - GitPython
    - ixmp4
    - nbclient
    - pytest
    - sphinx
    - xarray
    args: ["."]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.14
  hooks:
  - id: ruff
  - id: ruff-format
    args: [ --check ]
